#- hosts: all
#  tasks:
#    - authorized_key:
#        user: vagrant 
#        state: present
#        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

- hosts: all
  gather_facts: no
  tasks:
    - set_fact:
        rem_user: "{{ ansible_user | default(lookup('env','USER')) }}"
        rem_host: "{{ ansible_host }}"
    - local_action: command ssh-copy-id {{ rem_user }}@{{ rem_host }}
