---
#- name: Add an Apt signing key, uses whichever key is at the URL
#  apt_key:
#    url: http://apt.dockerproject.org/gpg
#    state: present
#
#- name: Agrego repositorio Docker
#  apt_repository:
#    repo: deb http://apt.dockerproject.org/repo ubuntu-xenial main
#    state: present
#    validate_certs: no

- name: Instalar paquetes útiles
  apt: name={{ item }} state=present
  with_items:
  - parted
  - vim
  - aptitude

#- name: instalar docker
#  shell: apt-get install -y - docker-engine --allow-unauthenticated