---

- name: Instalar kolla y kolla-ansible con pip
  pip:
    name: "{{ item }}"
  become: True
  with_items:
  - kolla
  - kolla-ansible

#- name: Clonar repo kolla
#  git:
#    repo: https://github.com/openstack/kolla.git
#    dest: /home/vagrant/kolla
#    version: "stable/{{ openstack_version }}"
#  become: yes
#  become_user: vagrant
#
#- name: Clonar repo kolla-ansible
#  git:
#    repo: https://github.com/gsanso/kolla-ansible.git
#    dest: /home/vagrant/kolla-ansible
#    version: "stable/{{ openstack_version }}"
#  become: yes
#  become_user: vagrant

- name: Clonar repo kolla-ansible-wdcs
  git:
    repo: https://github.com/gsanso/kolla-ansible-wdcs.git
    dest: /home/vagrant/kolla-ansible-wdcs
    version: master 
  become: yes
  become_user: vagrant

#- name: Clonar repo kolla-cli
#  git:
#    repo: https://github.com/openstack/kolla-cli.git
#    dest: /home/vagrant/kolla-cli
#    version: master
#  become: yes
#  become_user: vagrant

#- name: Instalar requerimientos para kolla
#  pip:
#    requirements: /home/vagrant/kolla/requirements.txt
#  become: true
#
#- name: Instalar requerimientos para kolla-ansible
#  pip:
#    requirements: /home/vagrant/kolla-ansible/requirements.txt
#  become: true

#- name: Instalar requerimientos para kolla-cli
#  pip:
#    requirements: /home/vagrant/kolla-cli/requirements.txt
#  become: true

#- name: Instalar kolla-cli
#  shell: "python /home/vagrant/kolla-cli/setup.py install"
#  become: true
#
#- name: Setup kolla-cli
#  shell: "python /home/vagrant/kolla-cli/cli_setup.py"
#  become: true

- name: Copiar fichero multinode (inventory)
  copy:
    src: multinode
    dest: /home/vagrant/multinode
  become: true

- name: Verifcar que el dir /etc/kolla exista
  file:
    path: /etc/kolla
    state: directory

- name: Verifcar que el dir /etc/kolla/config exista
  file:
    path: /etc/kolla/config
    state: directory

- name: Copiar fichero globals.yml (variables globales de kolla)
  #Aqui no utilizo template porque da error al parsear las vars del fichero
  copy:
    src: globals.yml
    dest: /etc/kolla/globals.yml
  become: true

- name: Copiar fichero passwords.yml
  copy:
    src: passwords.yml
    dest: /etc/kolla/passwords.yml
  become: true

#- name: Crear las ssh keys para el usuario en el deployer
- name: Crear key de ssh de 2048-bit
  user:
    name: vagrant
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa


- name: Generar las contraseñas
  shell: /usr/local/bin/kolla-genpwd
  become: true