---

- name: Instalar kolla y kolla-ansible con pip
  pip:
    name: "{{ item }}"
  become: True
  version: 6.1.1      #  version: 6.1.1     # Queens: 6.1.1 Pike: 5.0.3
  with_items:
  - kolla
  - kolla-ansible
  when: not install_from_git

- name: Clonar repo kolla-ansible-wdcs
  git:
    repo: https://github.com/gsanso/kolla-ansible-wdcs.git
    dest: "/home/{{ ansible_user }}/kolla-ansible-wdcs"
    version: master 
  become: yes
  become_user: vagrant

 #Según la documentacion hay que utilizar los repos de git solo si vamos a desarrollar

- name: Clonar repo kolla
  git:
    repo: https://github.com/openstack/kolla.git
    dest: "/home/{{ ansible_user }}/kolla"
    version: "stable/{{ openstack_version }}"
    #version: "master"
  become: yes
  become_user: vagrant
  when: install_from_git

- name: Clonar repo kolla-ansible
  git:
    repo: https://github.com/gsanso/kolla-ansible.git
    dest: "/home/{{ ansible_user }}/kolla-ansible"
    version: "stable/{{ openstack_version }}"
    #version: "master"
  become: yes
  become_user: vagrant
  when: install_from_git

- name: Instalar requerimientos para kolla
  pip:
    requirements:
  become: true
  with_items:
    - "/home/{{ ansible_user }}/kolla/requirements.txt"
    - "/home/{{ ansible_user }}/kolla-ansible/requirements.txt"
  when: install_from_git

- name: agregar kolla-ansible al PATH
  copy:
    dest: /etc/profile.d/kolla-ansible-path.sh
    content: 'PATH=$PATH:{{ ansible_user }}/kolla-ansible/tools'
  when: install_from_git

#- name: Fix para Ceilometer (sobreescribimos fichero extend_start.sh)
#  copy:
#    src: extend_start.sh
#    dest: /home/{{ ansible_user }}/kolla/docker/ceilometer/ceilometer-notification/extend_start.sh


#- name: Clonar repo kolla-cli
#  git:
#    repo: https://github.com/openstack/kolla-cli.git
#    dest: "/home/{{ ansible_user }}/kolla-cli"
#    version: master
#  become: yes
#  become_user: vagrant
#  when: enable_kolla_cli
#
#- name: Instalar requerimientos para kolla-cli
#  pip:
#    requirements: "/home/{{ ansible_user }}/kolla-cli/requirements.txt"
#  become: true
#
#- name: Instalar kolla-cli
#  shell: "python /home/{{ ansible_user }}/kolla-cli/setup.py install"
#  when: enable_kolla_cli
#
#- name: Setup kolla-cli
#  shell: "python /home/{{ ansible_user }}/kolla-cli/cli_setup.py"
#  when: enable_kolla_cli

- name: Copiar fichero multinode (inventory)
  copy:
    src: multinode
    dest: "/home/{{ ansible_user }}/multinode"
  become: yes
  become_user: vagrant

- name: Verifcar que el dir /etc/kolla/config exista
  file:
    path: /etc/kolla/config
    state: directory
    owner: vagrant

- name: Copiar fichero globals.yml (variables globales de kolla)
  #Aqui no utilizo template porque da error al parsear las vars del fichero
  copy:
    src: globals.yml
    dest: /etc/kolla/globals.yml

- name: Copiar fichero passwords.yml
  copy:
    src: passwords.yml
    dest: /etc/kolla/passwords.yml

- name: Copiar template para ceph.conf
  template:
    src: ceph.conf.j2
    dest: /etc/kolla/config/ceph.conf

# Crear las ssh keys para el usuario en el deployer
- name: Crear key de ssh de 2048-bit
  user:
    name: vagrant
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

- name: Generar las contraseñas
  shell: /usr/local/bin/kolla-genpwd
  become: true
  when: not install_from_git

- name: Generar las contraseñas
  shell: /home/{{ ansible_user }}/kolla-ansible/tools/generate_passwords.py
  become: true
  when: install_from_git