---
- name: Add Ansible repository
  apt_repository:
    repo: ppa:ansible/ansible

#- name: Install Python minimal
#  shell: apt-get install -y python-minimal
#  become: yes

- name: Install packages
  apt: name={{ item }} state=present
  become: yes
  with_items:
  - python-minimal
  - python2.7-dev
  - python-pip
  - ansible
  - sshpass
  - git
  - vim
  - aptitude
  - curl
  - telnet

- name: Remover paquetes conflictivos
  apt: name={{ item }} state=absent
  become: yes
  with_items:
  - python-ndg-httpsclient
  - python-openssl
