---
# Generate an OpenSSL private key with a different size (2048 bits)
- name: Generar clave privada
  openssl_privatekey:
    path: files/vagrant.pem
    size: 2048

- name: Add ssh user keys
  authorized_key: user={{ item.name }} key="{{ item.key }}"
  with_items: ssh_users

- name: create key directory
  action: file path=/etc/ssh/authorized_keys state=directory
    owner=0 group=0 mode=0755

- name: upload user key
  action: copy src=/home/ansible/etc/ssh/authorized_keys/{{ item }}
    dest=/etc/ssh/authorized_keys/
    owner=0 group=0 mode=644
  with_items: sshusers

- name: sshd configuration file update
  template: src=/etc/ansible/configs/etc/ssh/sshd_config.j2
    dest=/etc/ssh/sshd_config
    backup=yes
    owner=0 group=0 mode=0644
    validate='/usr/sbin/sshd -T -f %s'
  notify:
  - restart sshd