---

- name: Ensure a locale exists
  locale_gen:
    name: en_US.UTF-8
    state: present

- name: Grupo docker debe existir
  group:
    name: docker
    state: present

- name: Agregar usuario a grupo docker
  user:
    name: vagrant
    state: present
    groups: docker

- name: Copiar fichero de configuracion de Ansible
  template: src=ansible.cfg.j2 dest=/etc/ansible/ansible.cfg
  become: true