---
- name: Verifcar que el dir /etc/kolla exista
  file:
    path: /etc/kolla/certificates/private
    state: directory

- name: Generar los certificados
  shell: /usr/local/bin/kolla-ansible -i  /home/{{ ansible_user }}/multinode certificates
  become: true
  when: not install_from_git

- name: Generar los certificados
  shell: /home/vagrant/kolla-ansible/tools/kolla-ansible -i  /home/{{ ansible_user }}/multinode certificates
  become: true
  when: install_from_git